### ISSUE TITLE
Please Don't Use CloudSource. 😊 

### ISSUE THREAD

**Issue by NfNitLoop** [nimbul/cloudsource#1]
Hi @vadimj! It's been a while!

I appreciate you finally getting this open-sourced since (IIRC) we weren't able to get approval for that when I was at the NYT. Also appreciate being credited for my work.

But to anyone coming across this code, since my name is attached, I feel obligated to give a warning: Don't deploy your code like this! 😊  Instead, create installation packages appropriate for your environments.

This is a very old project that was written as a compromise given the technologies, policies and practices of the NYT organization at the time. 

Of course, I probably don't need to say any of this since this is a tool for Subversion hosted on **GitHub**. 😆

**Comment by vadimj** [comment]
Agree 100%! Deprecating the whole repo now, so folks are not confused! :)
Great to hear from you Cody!

**Comment by vadimj** [comment]
Oh, turns out I don't have access to the Nimbul NYT 'org' anymore. Perhaps @rabbitt can help!

I deprecated the repos I owned though, [nimbul](https://github.com/vadimj/nimbul) and [cloudmaster](https://github.com/vadimj/cloudmaster)

**Comment by rabbitt** [comment]
Sadly, I don't have access to the Nimbul NYT org either, but maybe @jonoden can help ?

**Comment by jonoden** [comment]
Hey guys, blast from the past! I'll see if I can track down the owner, thanks for the heads up.

**Comment by vadimj** [comment]
Happy New Year everyone! Jon - any luck in finding who the repo owners are ?

Vadim

**Comment by jonoden** [comment]
As this is so old and was spun up probably by a few people it's been a little hard to find someone. I'm working on seeing what we can do here.

**Comment by jonoden** [comment]
I was able to secure access, we'll review the repos and take appropriate action. Thanks for bringing this to our attention, I don't think anyone knew or remembered this org existed.

**Comment by vadimj** [comment]
Jon is THE man! Thanks Jon!
